### ISSUE TITLE
[Roadmap] UX Improvements to incentivise token savings

### ISSUE THREAD

**Issue by ffrappo** [enricoros/big-AGI#271]
**Why**
I propose the chat history is always visible on the left, with a "New conversation" button at the top, and "Start new chat" shortcut is placed near the message send area. On mobile, a button on the top right could do the job.
As a reinforcement, a "system notice" every 10 messages in the chat area could educate the users about the benefit of starting a new chat, perhaps using the summarisation feature.

**Concise description**
The current UI both in mobile and desktop hides away the previous chats and it's not so immediate to create new chats. This leads to an increased incentive for the user to remain in the same thread. This goes at the cost of token spend and context exhaustion.

**Requirements**
If you can, please detail the changes you expect in UX, user workflows, technology, architecture (if not, the reviewers will do it for you)

**Comment by enricoros** [comment]
I like the general tone and direction of this idea. While a new UI is in the plan (#201 #203 ), I like the idea of having specialized effort to save tokens.

In addition to a better UX to start chats, how about we add an *economy mode*?

E.g. features on the Economy mode:

- [ ] Cost prediction (given the precise token estimation and the llm cost per token) of the current prompt (range showing $input... $input+max_Output)
- [ ] Every 10 messages a reminder to start a new chat (or something similar, given messages can be of different sizes..)
- [ ] button to auto-hide messages (sliding window approach) past the Half or Quarter of the context window
- [ ] ...?

What do you think @ffrappo ?

**Comment by ffrappo** [comment]
That would be brilliant. But perhaps maintaining a new mode would be harder than adding a couple of defaults. Also Big Agi already does a lot and has tons of customisations, could become harder to pickup for new users if you add more settings and variants.

**Comment by enricoros** [comment]
See also #341

**Comment by enricoros** [comment]
Closing as shipped.

Shipped in v2: the chat list is a persistent drawer with New chat at the top, the composer shows tokens plus a cost range before you send, and any message can be excluded from context. Two items from my own list are not happening as written - the every-10-messages nag, and the auto-hide of messages past half the context window; that second one moves to #341 with the rest of the cost work. Thanks @ffrappo, this shaped the drawer. Closing.

@ffrappo this close comes from an automated backlog pass - if you disagree, feel free to reopen.
