### ISSUE TITLE
[Roadmap] Reply to specific parts of text

### ISSUE THREAD

**Issue by hardikbhatia777** [enricoros/big-AGI#504]
**Why**
Users should be able to (quickly) respond to certain parts of the AI response. Plain and simple feature, but massively improves QOL. 

**Description**
Much like ChatGPT, when a user selects a certain part of the conversation/reply, a small bubble should appear where clicking the bubble copies the highlighted text into the message box like so:

![image](https://github.com/enricoros/big-AGI/assets/98163873/ab9628a9-7bef-4805-abf5-a1e2743080b5)

And the message box should turn something like this:

![image](https://github.com/enricoros/big-AGI/assets/98163873/5d95c570-24f9-46c7-97d9-46637d295b00)

**Requirements**
Change to the message box to accommodate replies in some form, or maybe just copy the highlighted text to the message box. Personally I'd like the first option.  

- [X]  I'm willing to submit a pull request for this

**Comment by hardikbhatia777** [comment]
![image](https://github.com/enricoros/big-AGI/assets/98163873/6b15b92e-18f9-414b-85e5-c30374c5a51b)

This is another way of implementing this like Gemini. IMO, this is a bit overkill (in a good way) and completely doable, especially since this box already exists:

![image](https://github.com/enricoros/big-AGI/assets/98163873/28608aba-1b60-47a6-991a-6e8cb2d11d86)

**Comment by enricoros** [comment]
Hi @hardikbhatia777 did you make the second design? Looks really interesting and in the direction we'd love to implement this. Where can I see more of it?

**Comment by hardikbhatia777** [comment]
@enricoros I didn't, this is Gemini's interface. Glad you like the suggestion 🚀 

PS. I'm Seven on Discord :)

**Comment by enricoros** [comment]
I like Gemini's work on the UI. Of all the UIs it's the most similar to my thinking for Big-AGI. This is a feature I had in mind for a while, and it's half implemented on main. 
- OpenAI implements it by inserting a system prompt right after the user prompt, and that kind of behavior really only works for OpenAI (most vendors do not support more than 1 system prompt, especially in the middle of text)
- we'd have to abstract it for other models or disable the feature
- Gemini has interesting and clearly prioritized operations
- I'm trying to bring Beam on a selection level, which would be huge for remixing a paragraph with live preview; it's an easy feature that would just take a couple of days to implement but I don't have that kind of time now, would love for someone else to take it

**Comment by hardikbhatia777** [comment]
Thanks for your feedback. I'd be happy to take this up over next week. 

A small clarification - do you want the bubble over highlighted text like ChatGPT and Gemini have, or do you want this to be integrated within the right click menu which has copy, auto-diagram and speak functionalities?

**Comment by enricoros** [comment]
Hi Seven, you'll find the UI changes on the `main` branch half implemented, as I started last week. In the ChatMessage.tsx file there are flags up top to enable the context (right click) menu, or the new Overlay menu, which works on a selection.

I think the overlay is better but has less space, especially on mobile. The overlay can fit the new Reply function and the former context actions (Copy, Speak, draw, diagram), but not much more.

What do you think? I like the Gemini looks best, but many users (especially on Mac) never right click, so the 'overlay' presentation is best. Alternatively, it could be a multi-line menu.

Status of implementation:

- [x] selection overlay framework
- [x] showing the reply text on the Composer
- [ ] implementation of the reply-to function (OpenAI injects a system message that you can see in the network logs)
- [ ] implementation of "cut" (really useful)
- [ ] implementation of other functions (shrink, expand..)

**Comment by enricoros** [comment]
Fully implemented on unreleased branch.

**Comment by enricoros** [comment]
@hardikbhatia777 this is how it looks like:

![Image](https://github.com/enricoros/big-AGI/assets/32999/2ed0ba50-7f91-409b-bfaf-79e94b462011)

**Comment by hardikbhatia777** [comment]
Looks great!
